# Generated by Django 3.1.4 on 2020-12-16 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('english_name', models.CharField(max_length=200)),
                ('arabic_name', models.CharField(max_length=200)),
                ('created_by', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('created_date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('english_name', models.CharField(max_length=200)),
                ('arabic_name', models.CharField(max_length=200)),
                ('created_by', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('created_date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_english_name', models.CharField(max_length=200)),
                ('type_arabic_name', models.CharField(max_length=200)),
                ('created_by', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('created_date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_english_name', models.CharField(max_length=200)),
                ('unit_arabic_name', models.CharField(max_length=200)),
                ('created_by', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('created_date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_english_name', models.CharField(max_length=200)),
                ('section_arabic_name', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=100)),
                ('arabic_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('choose_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contentsManagement.type')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
