# Generated by Django 3.2.3 on 2021-06-15 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proudect_english_name', models.CharField(max_length=200)),
                ('proudect_arabic_name', models.CharField(max_length=200)),
                ('barcode_number', models.CharField(max_length=200)),
                ('proudect_company_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('english_name', models.CharField(max_length=200)),
                ('arabic_name', models.CharField(max_length=200)),
                ('created_by', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('english_name', models.CharField(max_length=200)),
                ('arabic_name', models.CharField(max_length=200)),
                ('created_by', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_english_name', models.CharField(max_length=200)),
                ('type_arabic_name', models.CharField(max_length=200)),
                ('created_by', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_english_name', models.CharField(max_length=200)),
                ('unit_arabic_name', models.CharField(max_length=200)),
                ('created_by', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('created_date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('step_on_english', models.CharField(max_length=200)),
                ('step_on_arabic', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_english_name', models.CharField(max_length=200)),
                ('section_arabic_name', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sauce_english_name', models.CharField(max_length=100)),
                ('sauce_arabic_name', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=100)),
                ('arabic_name', models.CharField(max_length=100)),
                ('recipe_info_english', models.CharField(default=None, max_length=200)),
                ('recipe_info_arabic', models.CharField(default=None, max_length=200)),
                ('total_time', models.CharField(default=None, max_length=100)),
                ('cooking_time', models.CharField(default=None, max_length=100)),
                ('preparation_time', models.CharField(default=None, max_length=100)),
                ('side_ingredients1', models.CharField(default=None, max_length=200)),
                ('side_ingredients2', models.CharField(default=None, max_length=200)),
                ('price', models.CharField(choices=[('Free', 'Free'), ('$1', '$1'), ('$2', '$2'), ('$3', '$3'), ('$4', '$4'), ('$5', '$5')], default=None, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('chef_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.chef')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ManyToManyField(null=True, to='contentsManagement.Ingredient')),
                ('kitchen_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contentsManagement.kitchen')),
                ('meal_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contentsManagement.mealtype')),
                ('sauce', models.ManyToManyField(to='contentsManagement.Sauce')),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contentsManagement.section')),
                ('steps', models.ManyToManyField(to='contentsManagement.Step')),
            ],
        ),
    ]
