# Generated by Django 3.1.4 on 2021-01-06 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentsManagement', '0002_auto_20210106_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='kitchen_type',
        ),
        migrations.AddField(
            model_name='recipe',
            name='kitchen_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contentsManagement.kitchen'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contentsManagement.mealtype'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='section',
        ),
        migrations.AddField(
            model_name='recipe',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contentsManagement.section'),
        ),
    ]
