# Generated by Django 3.1.4 on 2021-01-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentsManagement', '0003_auto_20210106_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='choose_type',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sauce',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='side_ingredients1',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='side_ingredients2',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
