# Generated by Django 3.1.4 on 2021-01-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentsManagement', '0004_auto_20210106_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proudect_english_name', models.CharField(max_length=200)),
                ('proudect_arabic_name', models.CharField(max_length=200)),
                ('barcode_number', models.CharField(max_length=200)),
                ('proudect_company_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(default=None, to='contentsManagement.Ingredient'),
        ),
    ]
