# Generated by Django 3.1.4 on 2021-01-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentsManagement', '0007_sauce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='sauce',
        ),
        migrations.AddField(
            model_name='recipe',
            name='sauce',
            field=models.ManyToManyField(to='contentsManagement.Sauce'),
        ),
    ]
