# Generated by Django 3.1.4 on 2021-01-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentsManagement', '0008_auto_20210109_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='price',
            field=models.CharField(choices=[('Free', 'Free'), ('1$', '1$'), ('2$', '2$'), ('3$', '3$'), ('4$', '4$')], default=None, max_length=100),
        ),
    ]
