# Generated by Django 3.1.4 on 2021-01-09 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contentsManagement', '0009_recipe_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='price',
            field=models.CharField(choices=[('Free', 'Free'), ('$1', '$1'), ('$2', '$2'), ('$3', '$3'), ('$4', '$4'), ('$5', '$5')], default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('step_on_english', models.CharField(max_length=200)),
                ('step_on_arabic', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentsManagement.recipe')),
            ],
        ),
    ]
