# Generated by Django 3.1.4 on 2021-01-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentsManagement', '0010_auto_20210109_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='recipe',
            new_name='recipe_related',
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.ManyToManyField(to='contentsManagement.Step'),
        ),
    ]
