# Generated by Django 3.1.4 on 2021-01-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentsManagement', '0012_remove_step_recipe_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(to='contentsManagement.Ingredient'),
        ),
    ]
