# Generated by Django 3.1.4 on 2021-01-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentsManagement', '0014_auto_20210109_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='created_date',
        ),
    ]
