# Generated by Django 3.1.4 on 2021-01-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentsManagement', '0015_remove_type_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='created_date',
        ),
    ]
