# Generated by Django 3.1.4 on 2021-01-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentsManagement', '0016_remove_kitchen_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtype',
            name='created_date',
        ),
    ]
